name: .NET

on:
  push:
    branches: [ master ]
  create:
    tags:
     - '*'
     
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout dependencies
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.LibsRepository }}
        token: ${{ secrets.LibsRepositoryToken }}
        path: Dependencies
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Publish a release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ReModCE/bin/Release/ReModCE.dll
          ReModCE.Loader/bin/Release/ReModCE.Loader.dll
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}